version: '3'

services:
  eth-node:
    image: ethereum/client-go:v1.10.16
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "30303:30303"
      - "30303:30303/udp"
      - "8545:8545"
      - "8546:8546"
    volumes:
      - ./materials/nodes/${NETWORK}:/root/.ethereum/${NETWORK}
    command:
      --${NETWORK}
      --syncmode "light"
